Remove git workflows

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -1,42 +1,42 @@
-name: e2e
+# name: e2e
 
-on:
-  pull_request:
-  push:
-    branches:
-      - 'master'
+# on:
+#   pull_request:
+#   push:
+#     branches:
+#       - 'master'
 
-permissions:
-  contents: read
+# permissions:
+#   contents: read
 
-jobs:
-  kind-helm:
-    strategy:
-      matrix:
-        helm-version:
-          - v3.11.0
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Setup Kubernetes
-        uses: helm/kind-action@v1.5.0
-        with:
-          version: v0.17.0
-          cluster_name: kind
-      - name: Build container image
-        run: |
-          ./test/build.sh
-          kind load docker-image test/podinfo:latest
-      - name: Setup Helm
-        uses: azure/setup-helm@v3
-        with:
-          version: ${{ matrix.helm-version }}
-      - name: Deploy
-        run: ./test/deploy.sh
-      - name: Run integration tests
-        run: ./test/test.sh
-      - name: Debug failure
-        if: failure()
-        run: |
-          kubectl logs -l app=podinfo || true
+# jobs:
+#   kind-helm:
+#     strategy:
+#       matrix:
+#         helm-version:
+#           - v3.11.0
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v3
+#       - name: Setup Kubernetes
+#         uses: helm/kind-action@v1.5.0
+#         with:
+#           version: v0.17.0
+#           cluster_name: kind
+#       - name: Build container image
+#         run: |
+#           ./test/build.sh
+#           kind load docker-image test/podinfo:latest
+#       - name: Setup Helm
+#         uses: azure/setup-helm@v3
+#         with:
+#           version: ${{ matrix.helm-version }}
+#       - name: Deploy
+#         run: ./test/deploy.sh
+#       - name: Run integration tests
+#         run: ./test/test.sh
+#       - name: Debug failure
+#         if: failure()
+#         run: |
+#           kubectl logs -l app=podinfo || true
